twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        notification: '@Infrastructure\Symfony\Service\Notification\NotificationService'
