version: '3.3'
services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www:delegated
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    user: '${USER_ID}:${GROUP_ID}'
    restart: unless-stopped
    image: grafikart/php:1.0.3
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
    environment:
      APP_ENV: dev
      MAIL_DSN: sendmail://default
      MESSENGER_TRANSPORT_DSN: redis://redis:6379/messages
      MESSENGER_TRANSPORT_FAILED_DSN: redis://redis:6379/messages_failed
      MERCURE_SUBSCRIBER_KEY: mercure_subscriber
  db:
    restart: unless-stopped
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT__USER: root
      MYSQL_ROOT__DB: grafikart
  # Dev tools
  adminer:
    image: adminer
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8888:8080
  mail:
    image: mailhog/mailhog
    ports:
      - 1080:8025
 #node:
 #  user: '${USER_ID}:${GROUP_ID}'
 #  build:
 #    context: ./tools/docker/node
 #  command: yarn run dev
 #  working_dir: /usr/src/app
 #  volumes:
 #    - .:/usr/src/app
 #  ports:
 #    - 3000:3000
volumes:
  db-data:
    driver: local
  search-data:
    driver: local
