controllers:
    resource: ../../src/Controller/
    type: annotation

admin_controllers:
    resource: ../../src/Controller/Admin/
    name_prefix: admin_
    prefix: /admin
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
