controllers:
    resource: ../../src/UserInterface/Controller/
    type: annotation

admin_controllers:
    resource: ../../src/UserInterface/Controller/Admin/
    name_prefix: admin_
    prefix: /admin
    type: annotation

kernel:
    resource: ../../src/Infrastructure/Symfony/Kernel.php
    type: annotation
